name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main  # change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/www/html/your-laravel-folder
          git pull origin main
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:clear
