version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel_network
    command: >
      sh -c "php artisan migrate --force &&
             php artisan storage:link &&
             apache2-foreground"

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE=bsip
      MYSQL_USER=root
      MYSQL_PASSWORD=""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:

environment:
  PHP_MEMORY_LIMIT: 512M
  PHP_UPLOAD_MAX_FILESIZE: 100M
  PHP_POST_MAX_SIZE: 100M
  PHP_MAX_EXECUTION_TIME: 300